apiVersion: v1
kind: ConfigMap
metadata:
  name: recruitment-app-config
data:
  NODE_ENV: "production"
  PORT: "3000"
  DB_NAME: "hr_system"
  LOG_LEVEL: "info"
  DEFAULT_ADMIN_ID: "project"
  DEFAULT_ADMIN_PASSWORD: "project123"
  MONGO_URI: "mongodb://rootuser:rootpassword@mongodb-service:27017/hr_system?authSource=admin"
  MONGO_USERNAME: "rootuser"
  MONGO_PASSWORD: "rootpassword"
